// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ithome.proto

package ithome

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Greeting             string                `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	MailCount            *wrappers.DoubleValue `protobuf:"bytes,2,opt,name=mail_count,json=mailCount,proto3" json:"mail_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ithome_20cb34816137b9e8, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func (m *HelloRequest) GetMailCount() *wrappers.DoubleValue {
	if m != nil {
		return m.MailCount
	}
	return nil
}

type HelloResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ithome_20cb34816137b9e8, []int{1}
}
func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (dst *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(dst, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/HelloService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HelloService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ithome.proto",
}

func init() { proto.RegisterFile("ithome.proto", fileDescriptor_ithome_20cb34816137b9e8) }

var fileDescriptor_ithome_20cb34816137b9e8 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xcd, 0x4b, 0x80, 0x40,
	0x10, 0x47, 0x31, 0x28, 0x74, 0xd2, 0x0e, 0x4b, 0x07, 0x91, 0x08, 0x11, 0x02, 0xbb, 0xac, 0x60,
	0xa7, 0xe8, 0x58, 0x87, 0xce, 0x0a, 0x5d, 0x63, 0x95, 0x69, 0x5b, 0x58, 0x9d, 0x6d, 0x3f, 0x0a,
	0xff, 0xfb, 0xf0, 0xa3, 0xa8, 0xe3, 0xdb, 0xfd, 0x31, 0xef, 0x41, 0xaa, 0xfc, 0x3b, 0x4d, 0xc8,
	0x8d, 0x25, 0x4f, 0xc5, 0xb5, 0x24, 0x92, 0x1a, 0x9b, 0x8d, 0x86, 0xf0, 0xd6, 0x7c, 0x59, 0x61,
	0x0c, 0x5a, 0xb7, 0xff, 0x57, 0x12, 0xd2, 0x67, 0xd4, 0x9a, 0x3a, 0xfc, 0x08, 0xe8, 0x3c, 0x2b,
	0x20, 0x96, 0x16, 0xd1, 0xab, 0x59, 0xe6, 0x51, 0x19, 0xd5, 0x49, 0xf7, 0xcb, 0xec, 0x01, 0x60,
	0x12, 0x4a, 0xbf, 0x8e, 0x14, 0x66, 0x9f, 0x9f, 0x94, 0x51, 0x7d, 0xde, 0x5e, 0xf1, 0x5d, 0xc0,
	0x7f, 0x04, 0xfc, 0x89, 0xc2, 0xa0, 0xf1, 0x45, 0xe8, 0x80, 0x5d, 0xb2, 0xee, 0x1f, 0xd7, 0x79,
	0x75, 0x03, 0xd9, 0x21, 0x72, 0x86, 0x66, 0x87, 0xec, 0x12, 0x4e, 0x2d, 0x1a, 0xbd, 0x1c, 0x9a,
	0x1d, 0xda, 0xfb, 0xa3, 0xa7, 0x47, 0xfb, 0xa9, 0x46, 0x64, 0xb7, 0x10, 0xf7, 0x62, 0xd9, 0x9e,
	0x58, 0xc6, 0xff, 0xa6, 0x16, 0x17, 0xfc, 0xdf, 0xc1, 0xe1, 0x6c, 0x4b, 0xb8, 0xfb, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x82, 0x9b, 0xdc, 0xaf, 0x01, 0x01, 0x00, 0x00,
}
